version: "3.8"

services:
  rekeningcrapetools:
    build:
      context: .
    volumes:
      # Sync the working directory with the `/app` directory in the container
      - .:/app
      # Exclude the project virtual environment from being synced into the container
      - ./.venv:/app/.venv
    environment:
      - PYTHONUNBUFFERED=1
    command: streamlit run app.py
    ports:
      - "8501:8501"
